### PR TITLE
Fix/batch backfill v18

### PR DESCRIPTION
**Pull request by DavidWeiss2**
## Change Summary
The current batch mechanism is failing on Firestore big collections with a function crash.
This PR fixing this issue.

Also on this PR -
Better comments for failing batch (the current one get trimmed when multiple errors)

but for v18

## PR Checklist

- [x] I have read and signed the [Contributor License Agreement](https://forms.gle/PZyiY5N2GDQU8GsV9).

### CODE REVIEW

**Comment by DavidWeiss2** [comment]
Saw the conflicts, fixing them.

**Comment by DavidWeiss2** [comment]
@jasonbosco Conflict resolved

**Review by jasonbosco — CHANGES_REQUESTED** [review]
Looks like tests are failing

**Comment by tharropoulos** [comment]
On https://github.com/typesense/firestore-typesense-search/pull/70/commits/30105bcdb5ddd131fbd71e8f500907f1ba526306 , there was a change introduced on line 53, regarding the `currentDocumentsBatch` variable 
```js
const currentDocumentsBatch = thisBatch.docs.map((doc) => utils.typesenseDocumentFromSnapshot(doc));
 ```
This implementation resulted in currentDocumentsBatch being an array of pending promises, as `typesenseDocumentFromSnapshot` is an [asynchronous function](https://github.com/DavidWeiss2/firestore-typesense-search/blob/b8d920728880ea3b6170c1445464dc2108ed088f/functions/src/utils.js#L26-L51) (Although only because of the dynamic import of `flat`).

So, changing this line to 
```js
const currentDocumentsBatch = await Promise.all(thisBatch.docs.map(async (doc) => {
  return await utils.typesenseDocumentFromSnapshot(doc);
}));
```
takes care of the issue, resolving to the corresponding document schema that the `import` endpoint expects.

**Comment by tharropoulos** [comment]
Rebased master into the branch, can now target master.

**Comment by DavidWeiss2** [comment]
What needed to fix in this PR in order to merge it?

**Review by jasonbosco — APPROVED** [review]

**Comment by jasonbosco** [comment]
This is now available in [v1.5.0-rc.1](https://github.com/typesense/firestore-typesense-search/releases/tag/v1.5.0-rc.1). 

The installation link for this RC build is in the link above.

**Pull request merged**
