### PR TITLE
Support for subcategory backfill (redo)

### PR DESCRIPTION
**Pull request by vazome**
## Change Summary
@vazome – Improves upon https://github.com/typesense/firestore-typesense-search/pull/72. I took into account that orginal file was renamed and put subcategory backfill logic explanation into REAME.
Tested this change in Cloud Functions, it works.

@guenth39 – With these changes, the backfill will now work also for subcollections, not only for "root" collection. If the collection path is something like users/{userId}/items the sync has already worked, but the backfill did not as the documents were queried with this collection path, but that did not work. Instead, we use the collectionGroup feature now with only the last part of the path.

## PR Checklist

- [x] I have read and signed the [Contributor License Agreement](https://forms.gle/PZyiY5N2GDQU8GsV9).

### CODE REVIEW

**Comment by vazome** [comment]
It closes: https://github.com/typesense/firestore-typesense-search/issues/17

**Comment by vazome** [comment]
FYI @guenth39 @jasonbosco

**Review by jasonbosco — CHANGES_REQUESTED** [review]
@vazome Thank you for the PR! Could you add an integration test with a sub-collection?

**Comment by vazome** [comment]
@jasonbosco could you please elaborate, I should make test in the code itself or something different?

**Comment by jasonbosco** [comment]
You want to create a new test file like [this one](https://github.com/typesense/firestore-typesense-search/blob/master/test/indexOnWriteWithoutFlattening.spec.js) that reads the collection name configuration from new test params file [like this](https://github.com/typesense/firestore-typesense-search/blob/22311df3d83caf890ed9b3cc566053b16c4efda1/extensions/test-params-flatten-nested-true.local.env), but has a nested collection name specified in it. 

And then update the test runner [here](https://github.com/typesense/firestore-typesense-search/blob/22311df3d83caf890ed9b3cc566053b16c4efda1/package.json#L8-L9) and add a test part 3 may be, to run the test in CI

**Comment by vazome** [comment]
@jasonbosco tests included, please verify

**Comment by vazome** [comment]
Okay, I see the errors

**Comment by vazome** [comment]
Corrected the wrong indent and missing new line

**Comment by tharropoulos** [comment]
Hey, I saw that the tests were [failing](https://github.com/typesense/firestore-typesense-search/actions/runs/11879541506/job/33102097018?pr=93#step:9:695), so I took a closer look and tried to debug it myself. Turns out, if you log the value:

```ts
      const typesenseDocsStr = await typesense.collections(encodeURIComponent(typesenseSubcollectionName)).retrieve();
      console.dir(typesenseDocsStr);
```
The collection has no documents present:
```js
    {
      created_at: 1731922232,
      default_sorting_field: '',
      enable_nested_fields: true,
      fields: [
        {
          facet: false,
          index: true,
          infix: false,
          locale: '',
          name: '.*',
          optional: true,
          sort: false,
          stem: false,
          store: true,
          type: 'auto'
        }
      ],
      name: 'books_firestore/1/subcollection',
      num_documents: 0,
      symbols_to_index: [],
      token_separators: []
    }
```
What's also interesting is one in two runs, the test fails to delete the existing collection, resulting in a 409 from the server

**Comment by jsasitorn** [comment]
#99 was merged, and latest builds should support subcollections now

**Pull request closed without merging**
